TARGET = EVA2RT
ATTR = PRX

OBJS = src/runtime/runtime_entry.o src/runtime/runtime_patch.o src/runtime/hook_write.o\
 src/runtime/patches/text_encoding_patch.o\
 src/runtime/patches/sentence_patch.o\
 src/runtime/patches/external_translation_patch.o\
 src/runtime/patches/font_patch.o\
 src/runtime/patches/savedata_patch.o\
 src/runtime/patches/message_dialog_patch.o\
 src/runtime/patches/debug_patch.o\
 src/runtime/patches/memtalk/memtalk_patch.o\
 src/runtime/patches/memtalk/memtalk_game_calls.o\
 src/runtime/patches/memtalk/memtalk_templates.o\
 src/transform.o src/bin/gb2312.o src/bin/sjis.o src/bin/utf16.o\
 src/utils/log.o src/sceLibFont.o src/scefttt.o src/psputil.o

CFLAGS = -O2 -G0 -Wall -fno-pic
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
LDFLAGS = -nostartfiles

ASFLAGS = -DF_sceLibFont_0000 -DF_sceLibFont_0003 -DF_sceLibFont_0014 -DF_sceLibFont_0017

INCDIR = include src/runtime/patches/memtalk

BUILD_PRX = 1
PRX_EXPORTS = src/runtime/exports_runtime.exp

ifdef DEBUG
CFLAGS += -DPSPDEBUG
endif

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
