/*
 * English translation string hook patch (pure C, no machine-code stubs).
 *
 * ENTRANS.BIN (generated by scripts/generate_entrans.py) is loaded at
 * runtime by the plugin:
 *
 *   - short strings are overwritten in place at their original RAM address
 *     (offset relative to EVA2_STD_BASE, same convention as EBTRANS.BIN);
 *   - long strings are stored in the plugin's own buffer and an address
 *     remap table (source RAM address -> translated string) is built.
 *
 * strlen / memcpy / memmove / strcpy entry points are redirected to C
 * implementations that first run the source pointer through the lookup.
 * These four cover all strings that travel through the game's libc copies;
 * game-specific functions that do byte-level string work without libc are
 * intentionally not hooked (translating those would need machine-code
 * trampolines, and correctness/readability matters more than coverage).
 *
 * All jump targets are computed from game_base at install time.
 *
 * ENTRANS.BIN layout (all little-endian):
 *   u32 magic 'ENBS'; u32 version(1);
 *   u32 num_overwrite; u32 num_remap;
 *   num_overwrite x { u32 offset; u32 size; u8 data[size aligned4] }
 *   num_remap      x { u32 source_ram; u32 len; u8 data[align4(len)] }
 */
#include <pspiofilemgr.h>
#include <psptypes.h>
#include <string.h>

#include "english_string_hook_patch.h"
#include "hook_write.h"
#include "runtime_log.h"

#define ENTRANS_PATH "disc0:/PSP_GAME/USRDIR/ENTRANS.BIN"
#define ENTRANS_MAGIC 0x53424e45u /* 'ENBS' */
#define ENTRANS_VERSION 1u

/* Game rodata/data address range (same as the CWCheat project). */
#define ENTRANS_DATA_BASE 0x089B4640u
#define ENTRANS_DATA_TOP 0x08A57DFCu

#define ENTRANS_MAX_REMAP 4096
#define ENTRANS_STRING_POOL_SIZE (128 * 1024)

typedef struct EntransRemap {
    u32 source;
    const char *dest;
} EntransRemap;

static u32 g_game_base;
static u32 g_remap_count;
static EntransRemap g_remap[ENTRANS_MAX_REMAP];
static char g_string_pool[ENTRANS_STRING_POOL_SIZE];
static u32 g_string_pool_used;

/* The remap table and range check use RAM addresses as they really are in
 * memory, i.e. game_base + (IDA_addr - EVA2_STD_BASE).  The BOOT.BIN ELF is
 * relocatable, so the loaded base differs from the IDA image base. */
#define ENTRANS_DATA_BASE_OFF (ENTRANS_DATA_BASE - EVA2_STD_BASE)
#define ENTRANS_DATA_TOP_OFF (ENTRANS_DATA_TOP - EVA2_STD_BASE)

/* ------------------------------------------------------------------ */
/* Lookup: binary search the remap table.                              */
/* ------------------------------------------------------------------ */

const char *EnStrLookup(const char *ptr)
{
    u32 addr = (u32)ptr;
    int lo;
    int hi;

    if (addr < g_game_base + ENTRANS_DATA_BASE_OFF ||
        addr > g_game_base + ENTRANS_DATA_TOP_OFF) {
        return ptr;
    }

    lo = 0;
    hi = (int)g_remap_count - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        u32 src = g_remap[mid].source;
        if (src < addr) {
            lo = mid + 1;
        } else if (src > addr) {
            hi = mid - 1;
        } else {
            return g_remap[mid].dest;
        }
    }
    return ptr;
}

/* ------------------------------------------------------------------ */
/* libc hooks: pure C, redirected from the patched game entries.       */
/* ------------------------------------------------------------------ */

static size_t EnStrlen(const char *s)
{
    const char *p = EnStrLookup(s);
    size_t n = 0;
    while (p[n]) {
        ++n;
    }
    return n;
}

static void *EnMemcpy(void *dst, const void *src, size_t n)
{
    return memcpy(dst, EnStrLookup((const char *)src), n);
}

static void *EnMemmove(void *dst, const void *src, size_t n)
{
    return memmove(dst, EnStrLookup((const char *)src), n);
}

static char *EnStrcpy(char *dst, const char *src)
{
    return strcpy(dst, EnStrLookup(src));
}

/* ------------------------------------------------------------------ */
/* Install                                                             */
/* ------------------------------------------------------------------ */

static void EnHookInstall(u32 game_base)
{
    /* strlen */
    HookWrite_Jump(HookWrite_GameAddr(game_base, 0x089a63d8), EnStrlen);
    HookWrite_Nop(HookWrite_GameAddr(game_base, 0x089a63dc));
    /* memcpy */
    HookWrite_Jump(HookWrite_GameAddr(game_base, 0x089a4820), EnMemcpy);
    HookWrite_Nop(HookWrite_GameAddr(game_base, 0x089a4824));
    /* memmove */
    HookWrite_Jump(HookWrite_GameAddr(game_base, 0x089ada00), EnMemmove);
    HookWrite_Nop(HookWrite_GameAddr(game_base, 0x089ada04));
    HookWrite_Nop(HookWrite_GameAddr(game_base, 0x089ada08));
    /* strcpy */
    HookWrite_Jump(HookWrite_GameAddr(game_base, 0x089a6340), EnStrcpy);
    HookWrite_Nop(HookWrite_GameAddr(game_base, 0x089a6344));
    /* horizontal slice menu character limit 24 -> 35 (pure data patch) */
    HookWrite_U32(HookWrite_GameAddr(game_base, 0x08979d9c), 0x28430024);
    HookWrite_U32(HookWrite_GameAddr(game_base, 0x08979db4), 0x34050023);
    HookWrite_U32(HookWrite_GameAddr(game_base, 0x08979dbc), 0xa0800023);
}

static const char *EntransPoolAppend(const u8 *data, u32 len)
{
    char *p;
    if (g_string_pool_used + len > ENTRANS_STRING_POOL_SIZE) {
        return NULL;
    }
    p = g_string_pool + g_string_pool_used;
    memcpy(p, data, len);
    g_string_pool_used += len;
    return p;
}

static void EntransLoad(u32 game_base, const char *path)
{
    SceUID fd;
    u32 magic;
    u32 version;
    u32 num_overwrite;
    u32 num_remap;
    u32 i;

    fd = sceIoOpen(path, PSP_O_RDONLY, 0777);
    if (fd < 0) {
        RuntimeLog_Printf("entrans: open %s failed (%08x)", path, (u32)fd);
        return;
    }

    if (sceIoRead(fd, &magic, sizeof(magic)) != (int)sizeof(magic) ||
        sceIoRead(fd, &version, sizeof(version)) != (int)sizeof(version) ||
        sceIoRead(fd, &num_overwrite, sizeof(num_overwrite)) != (int)sizeof(num_overwrite) ||
        sceIoRead(fd, &num_remap, sizeof(num_remap)) != (int)sizeof(num_remap)) {
        RuntimeLog_Printf("entrans: short header");
        sceIoClose(fd);
        return;
    }

    if (magic != ENTRANS_MAGIC || version != ENTRANS_VERSION) {
        RuntimeLog_Printf("entrans: bad magic/version %08x/%08x", magic, version);
        sceIoClose(fd);
        return;
    }

    for (i = 0; i < num_overwrite; ++i) {
        u32 off;
        u32 size;
        u8 buf[1024];
        if (sceIoRead(fd, &off, sizeof(off)) != (int)sizeof(off) ||
            sceIoRead(fd, &size, sizeof(size)) != (int)sizeof(size)) {
            RuntimeLog_Printf("entrans: short overwrite entry %u", i);
            sceIoClose(fd);
            return;
        }
        if (size > sizeof(buf)) {
            RuntimeLog_Printf("entrans: overwrite entry %u too large (%u)", i, size);
            sceIoClose(fd);
            return;
        }
        if (sceIoRead(fd, buf, size) != (int)size) {
            RuntimeLog_Printf("entrans: short overwrite data %u", i);
            sceIoClose(fd);
            return;
        }
        /* ENTRANS.BIN offsets are already relative to EVA2_STD_BASE
         * (ram_addr - 0x08804000), so the real address is game_base + off.
         * HookWrite_GameAddr must NOT be used here: it would subtract
         * EVA2_STD_BASE a second time and write to an invalid low address. */
        memcpy((void *)(game_base + off), buf, size);
    }

    for (i = 0; i < num_remap; ++i) {
        u32 source;
        u32 len;
        u8 buf[4096];
        const char *dst;
        if (sceIoRead(fd, &source, sizeof(source)) != (int)sizeof(source) ||
            sceIoRead(fd, &len, sizeof(len)) != (int)sizeof(len)) {
            RuntimeLog_Printf("entrans: short remap entry %u", i);
            sceIoClose(fd);
            return;
        }
        if (len > sizeof(buf)) {
            RuntimeLog_Printf("entrans: remap entry %u too large (%u)", i, len);
            sceIoClose(fd);
            return;
        }
        if (sceIoRead(fd, buf, len) != (int)len) {
            RuntimeLog_Printf("entrans: short remap data %u", i);
            sceIoClose(fd);
            return;
        }
        if (g_remap_count >= ENTRANS_MAX_REMAP) {
            RuntimeLog_Printf("entrans: too many remap entries");
            sceIoClose(fd);
            return;
        }
        dst = EntransPoolAppend(buf, len);
        if (dst == NULL) {
            RuntimeLog_Printf("entrans: string pool exhausted");
            sceIoClose(fd);
            return;
        }
        g_remap[g_remap_count].source = game_base + (source - EVA2_STD_BASE);
        g_remap[g_remap_count].dest = dst;
        ++g_remap_count;
    }

    sceIoClose(fd);
    RuntimeLog_Printf(
        "entrans: loaded %u overwrite, %u remap",
        num_overwrite,
        g_remap_count);
}

void EnglishStringHookPatch_Install(u32 game_base)
{
    g_game_base = game_base;
    g_remap_count = 0;
    g_string_pool_used = 0;
    EntransLoad(game_base, ENTRANS_PATH);
    EnHookInstall(game_base);
}
