/* Generated by scripts/staff/generate_staff_roll.py. Do not edit. */
#pragma once

#define STAFF_ROLL_EXTRA_ROW_BASE 214
#define STAFF_ROLL_EXTRA_ROW_COUNT 2
#define STAFF_ROLL_EXTRA_COMMAND_COUNT 2
#define STAFF_ROLL_ORIGINAL_COMMAND_COUNT 196
#define STAFF_ROLL_INSERT_INDEX 189
#define STAFF_ROLL_EXTENDED_COMMAND_COUNT \
    (STAFF_ROLL_ORIGINAL_COMMAND_COUNT + STAFF_ROLL_EXTRA_COMMAND_COUNT)
#define STAFF_ROLL_ATLAS_NAME "staff21"

static const StaffScrollCmd g_staffRollExtraCommands[STAFF_ROLL_EXTRA_COMMAND_COUNT] = {
    {0x00100208u, 214, -1},
    {0x00000208u, 215, -1},
};
