#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


TEMPLATE_COUNT = 0x6D6


def c_utf8_string(text: str) -> str:
    if not text:
        return '""'
    if "\x00" in text:
        raise ValueError(f"template string contains a NUL character: {text!r}")
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def read_rows(path: Path):
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            template_id = int(row["id"])
            if template_id < 0 or template_id >= TEMPLATE_COUNT:
                raise ValueError(f"template id out of range: {template_id}")
            yield template_id, row["subject_policy"], row["zh_prefix"], row["zh_suffix"]


def write_c(rows, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by scripts/memtalk_generate_c_templates.py. */\n")
        f.write("/* Template strings stay UTF-8 here; cn_memtalk.c converts one template to EVA SJIS when rendering. */\n")
        f.write('#include "../cn_memtalk.h"\n\n')
        f.write("const CnMemTalkTemplatePair g_cnMemTalkTemplates[CN_MEMTALK_TEMPLATE_COUNT] = {\n")
        for template_id, subject_policy, prefix, suffix in rows:
            policy = (
                "CN_MEMTALK_SUBJECT_MANUAL"
                if subject_policy == "manual"
                else "CN_MEMTALK_SUBJECT_AUTO"
            )
            f.write(
                f"    [{template_id}] = {{{policy}, {c_utf8_string(prefix)}, {c_utf8_string(suffix)}}},\n"
            )
        f.write("};\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate EVA SJIS C MemTalk template data from the TSV workbook")
    parser.add_argument("--tsv", default="docs/memtalk_template_translation_workbook.tsv")
    parser.add_argument(
        "--output",
        default="third_party/EVA2PSPMod/source/PSPModBase/translation/cn_memtalk_templates.c",
    )
    args = parser.parse_args()

    rows = list(read_rows(ROOT / args.tsv))
    write_c(rows, ROOT / args.output)
    print(f"rows={len(rows)}")
    print(args.output)


if __name__ == "__main__":
    main()
