#!/usr/bin/env python3

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_COUNT = 0x6D6
DEFAULT_INPUT = Path("temp/downloads/utf8/memtalk.json")
DEFAULT_OUTPUT = Path("plugin/src/runtime/patches/memtalk/memtalk_templates.c")
CONTEXT_PATTERN = re.compile(r"^subjectPolicy: (auto|manual)$")


def c_utf8_string(text: str) -> str:
    if "\x00" in text:
        raise ValueError("template string contains a NUL character")
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def normalize_translation(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\\n", "\n")


def split_translation(text: str) -> tuple[str, str]:
    normalized = normalize_translation(text).rstrip("\n")
    if not normalized:
        raise ValueError("translation is empty")
    prefix, separator, suffix = normalized.partition("\n")
    return prefix, suffix if separator else ""


def validate_placeholders(text: str, template_id: int) -> None:
    remaining = text.replace("{A}", "").replace("{B}", "")
    if "{" in remaining or "}" in remaining:
        raise ValueError(f"template {template_id} contains an unsupported placeholder")


def read_rows(path: Path) -> list[tuple[int, str, str, str]]:
    with path.open("r", encoding="utf-8") as input_file:
        data = json.load(input_file)

    if not isinstance(data, list):
        raise ValueError("MemTalk input must be a JSON array")

    rows = []
    seen_ids = set()
    for item in data:
        if not isinstance(item, dict):
            raise ValueError("each MemTalk entry must be a JSON object")

        try:
            template_id = int(item["key"])
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError("MemTalk entry has an invalid key") from exc

        if template_id < 0 or template_id >= TEMPLATE_COUNT:
            raise ValueError(f"template id out of range: {template_id}")
        if template_id in seen_ids:
            raise ValueError(f"duplicate template id: {template_id}")
        seen_ids.add(template_id)

        translation = item.get("translation")
        if not isinstance(translation, str):
            raise ValueError(f"template {template_id} has no translation")

        context = item.get("context")
        match = CONTEXT_PATTERN.fullmatch(context or "")
        if not match:
            raise ValueError(f"template {template_id} has an invalid subject policy")

        prefix, suffix = split_translation(translation)
        validate_placeholders(prefix, template_id)
        validate_placeholders(suffix, template_id)
        rows.append((template_id, match.group(1), prefix, suffix))

    rows.sort(key=lambda row: row[0])
    return rows


def render_c(rows: list[tuple[int, str, str, str]]) -> str:
    lines = [
        "/* Generated by scripts/memtalk/memtalk_generate_c_templates.py. */",
        "/* Template strings stay UTF-8 here; memtalk_patch.c converts them to EVA SJIS when rendering. */",
        '#include "memtalk_patch.h"',
        "",
        "const CnMemTalkTemplatePair g_cnMemTalkTemplates[CN_MEMTALK_TEMPLATE_COUNT] = {",
    ]
    for template_id, subject_policy, prefix, suffix in rows:
        policy = (
            "CN_MEMTALK_SUBJECT_MANUAL"
            if subject_policy == "manual"
            else "CN_MEMTALK_SUBJECT_AUTO"
        )
        lines.append(
            f"    [{template_id}] = "
            f"{{{policy}, {c_utf8_string(prefix)}, {c_utf8_string(suffix)}}},"
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as output_file:
            output_file.write(content)
            temp_path = Path(output_file.name)
        os.replace(temp_path, path)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink()


def generate(input_path: Path, output_path: Path) -> int:
    rows = read_rows(input_path)
    write_atomic(output_path, render_c(rows))
    return len(rows)


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Runtime MemTalk C template table from ParaTranz JSON"
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    input_path = resolve_path(args.input)
    output_path = resolve_path(args.output)
    row_count = generate(input_path, output_path)
    print(f"Generated {row_count} MemTalk templates: {output_path}")


if __name__ == "__main__":
    main()
